### ISSUE TITLE
How to check work  correctly

### ISSUE THREAD

**Issue by balfabb87** [calasanmarko/TurboMac#1]
How to check work  correctly?

**Comment by calasanmarko** [comment]
It should be a pretty noticeable difference in performance - especially if you're trying to fix performance with a dead battery.

Try typing `kextstat | grep TurboMac` in the terminal. If it doesn't show up then it isn't running.

If it does show up and you're still unsure whether it's working, try installing Intel PowerGadget and posting a screenshot. The frequency should regularly flatline at the maximum.

Either way, follow up if you have any issues. Data on which Mac you're using would be appreciated (keep in mind this doesn't work on M1 Macs).

**Comment by calasanmarko** [comment]
I just noticed you've forked my repository a few commits ago, at a point where I had mistakenly put a faulty release in the Build folder which doesn't work at all.

Try installing the one in the most recent commit.
