### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by caballerofelipe** [calasanmarko/TurboMac#10]
I'm using macOS 11.6.8

My situation, posted on (https://apple.stackexchange.com/a/436745/66935):

> This didn't fix my issue. I have a Macbook Pro Retina 15" (Late 2013 / MacBookPro11,3). I changed the battery some time ago and then it said there was no battery installed, I guess the problem is that it doesn't detect it since some times (like during boot) I can remove the cable and the screen doesn't turn off. I think my computer has some problem with the SMC or something like that... I guess my problem is similar to what's fixed on this video (https://www.youtube.com/watch?v=6gme0ISQrcs).

Also, poste on (https://apple.stackexchange.com/a/415982/66935):
> I didn't actually try this since I used ./voltageshift read 0x199and it returned x2600 which sounds like it's the actually correct number for my CPU, but I don't know much about that so I didn't feel confident enough to keep tinkering. From [github.com/calasanmarko/TurboMac](https://github.com/calasanmarko/TurboMac) it states that it also tinkers with MSR 0x774 but when trying ./voltageshift read 0x199 it reboots instantly my computer.

I could provide logs if you can tell me where to look or more information...

**Comment by mndhvn** [comment]
Continued at https://github.com/calasanmarko/TurboMac/issues/9
