### ISSUE TITLE
Please add uninstall instruction

### ISSUE THREAD

**Issue by andrey-str** [calasanmarko/TurboMac#4]

**Comment by calasanmarko** [comment]
Uninstallation scripts and instructions have been added as of v1.0.1b, or https://github.com/calasanmarko/TurboMac/commit/adb40b51b616de431c929aacf5b1a30d478aa079.

If you installed the extension prior to the introduction of the installation script in https://github.com/calasanmarko/TurboMac/commit/f51fbd6ae8e6cb4b41bfd7733e6ecd3eb8143e7c, you will also need to manually restore `IOPlatformPluginFamily.kext` from wherever you put it back into `/System/Library/Extensions`.
